name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    uses: andreaTP/std-uritemplate/.github/workflows/test.yaml@extract-csharp
    # TODO: fix me
    # uses: std-uritemplate/std-uritemplate/.github/workflows/test.yaml@main
